//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dragon_Audio_Player.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dragon_Audio_Player.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete these file(s).
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete_these_file_s_ {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_delete_these_file_s_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder containing audio files.
        /// </summary>
        internal static string Click_Select_a_folder_containing_audio_files {
            get {
                return ResourceManager.GetString("Click_Select_a_folder_containing_audio_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete current playlist?.
        /// </summary>
        internal static string Delete_current_playlist_ {
            get {
                return ResourceManager.GetString("Delete_current_playlist_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file(s)?.
        /// </summary>
        internal static string Delete_file_s__ {
            get {
                return ResourceManager.GetString("Delete_file_s__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to load settings:
        ///.
        /// </summary>
        internal static string Error_MainForm_LoadFromSettings {
            get {
                return ResourceManager.GetString("Error_MainForm_LoadFromSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to save settings:
        ///.
        /// </summary>
        internal static string Error_MainForm_SetSettings {
            get {
                return ResourceManager.GetString("Error_MainForm_SetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to play next song:
        ///.
        /// </summary>
        internal static string ErrorPlayingNextSong {
            get {
                return ResourceManager.GetString("ErrorPlayingNextSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading error.
        /// </summary>
        internal static string MainForm_LoadFromSettings_Loading_error {
            get {
                return ResourceManager.GetString("MainForm_LoadFromSettings_Loading_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed playlists:
        ///.
        /// </summary>
        internal static string MainForm_LoadPlaylists_ {
            get {
                return ResourceManager.GetString("MainForm_LoadPlaylists_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed playlists.
        /// </summary>
        internal static string MainForm_LoadPlaylists_Fixed_playlists {
            get {
                return ResourceManager.GetString("MainForm_LoadPlaylists_Fixed_playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed playlists:
        ///.
        /// </summary>
        internal static string MainForm_LoadPlaylists_FixedPlaylistsColon {
            get {
                return ResourceManager.GetString("MainForm_LoadPlaylists_FixedPlaylistsColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to Seek to value: .
        /// </summary>
        internal static string MainForm_Seek_Error_trying_to_Seek_to_value__ {
            get {
                return ResourceManager.GetString("MainForm_Seek_Error_trying_to_Seek_to_value__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  milliseconds
        ///.
        /// </summary>
        internal static string MainForm_Seek_Milliseconds {
            get {
                return ResourceManager.GetString("MainForm_Seek_Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek error.
        /// </summary>
        internal static string MainForm_Seek_Seek_error {
            get {
                return ResourceManager.GetString("MainForm_Seek_Seek_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving error.
        /// </summary>
        internal static string MainForm_SetSettings_Saving_error {
            get {
                return ResourceManager.GetString("MainForm_SetSettings_Saving_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred in .
        /// </summary>
        internal static string MainForm_ShowUnexpectedErrorMessage_An_unexpected_error_occurred_in_ {
            get {
                return ResourceManager.GetString("MainForm_ShowUnexpectedErrorMessage_An_unexpected_error_occurred_in_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        internal static string MainForm_ShowUnexpectedErrorMessage_Unexpected_error {
            get {
                return ResourceManager.GetString("MainForm_ShowUnexpectedErrorMessage_Unexpected_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to stop audio:
        ///.
        /// </summary>
        internal static string MainForm_Stop_ {
            get {
                return ResourceManager.GetString("MainForm_Stop_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next song error.
        /// </summary>
        internal static string MainForm_tbarPlaying_ValueChanged_Next_song_error {
            get {
                return ResourceManager.GetString("MainForm_tbarPlaying_ValueChanged_Next_song_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to play next song:
        ///.
        /// </summary>
        internal static string MainForm_tbarPlaying_ValueChanged_NextSongError {
            get {
                return ResourceManager.GetString("MainForm_tbarPlaying_ValueChanged_NextSongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a playlist name..
        /// </summary>
        internal static string miPlaylistNewCreate_Please_enter_a_playlist_name_ {
            get {
                return ResourceManager.GetString("miPlaylistNewCreate_Please_enter_a_playlist_name_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New playlist created.
        /// </summary>
        internal static string New_playlist_created {
            get {
                return ResourceManager.GetString("New_playlist_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string PlayingStatus_Stopped {
            get {
                return ResourceManager.GetString("PlayingStatus_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  created!.
        /// </summary>
        internal static string Playlist_created {
            get {
                return ResourceManager.GetString("Playlist_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist name.
        /// </summary>
        internal static string Playlist_name {
            get {
                return ResourceManager.GetString("Playlist_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist with this name already exists.
        /// </summary>
        internal static string Playlist_with_this_name_already_exists {
            get {
                return ResourceManager.GetString("Playlist_with_this_name_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shield {
            get {
                object obj = ResourceManager.GetObject("Shield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped files.
        /// </summary>
        internal static string Skipped_files {
            get {
                return ResourceManager.GetString("Skipped_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping error.
        /// </summary>
        internal static string Stopping_error {
            get {
                return ResourceManager.GetString("Stopping_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume: {0}.
        /// </summary>
        internal static string Volume___0_ {
            get {
                return ResourceManager.GetString("Volume___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing error.
        /// </summary>
        internal static string Writing_error {
            get {
                return ResourceManager.GetString("Writing_error", resourceCulture);
            }
        }
    }
}
